<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsSampleProject>true</IsSampleProject>
    <Nullable>enable</Nullable>
    <RootNamespace>BasicApp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Firewall.AspNetCore\Firewall.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\Firewall.Providers.Cloudflare\Firewall.Providers.Cloudflare.csproj" />
    <ProjectReference Include="..\..\src\Firewall.OpenTelemetry\Firewall.OpenTelemetry.csproj" />
    <ProjectReference Include="..\..\src\Firewall.HealthChecks\Firewall.HealthChecks.csproj" />
  </ItemGroup>

</Project>
